### ISSUE TITLE
Different works under one DOI in BHL

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#102]
The opposite case to having duplicated DOIs for one work.

Pearse, A. S. (Ed.) (1936): Zoological names. A list of phyla, classes, and orders, prepared for section F, American Association for the Advancement of Science. First edition.

The landing page is for the first edition (1936) and has the DOI https://doi.org/10.5962/bhl.title.6792

Problem: Also the second (1947) and the fourth (1949) editions are on the landing page of the first edition. The third edition (1948) is missing.

**Comment by rdmpage** [comment]
@Archilegt I would interpret the DOI here to be at the level of title, that is, it applies to every volume/edition of the work. I realise that landing page mentions just the date of the first edition - this is something that could be fixed.

That the third edition is missing is simply that nobody has scanned it yet. You can ask for an item to be scanned here: https://about.biodiversitylibrary.org/ufaqs/can-i-submit-a-request-for-digitization/

**Comment by Archilegt** [comment]
Hi, Rod. There are significant differences among editions and they should not be represented by just one DOI. BHL has to apply different DOIs consistently to different editions. Otherwise people will go crazy. If different editions were meant to be represented by just one DOI, then I should have reported #98 as triplicated rather than duplicated BHL DOIs.

About the "scanning request page": As I wrote in another issue, [BHL's scanning request form](https://www.biodiversitylibrary.org/contact#/request) is broken. Did Mike L. fix it? He has not commented again under that issue, but the answer is no. I tried again and wasted my time. One doesn't find that the page is broken until the end. I am very tired of not having a direct communication channel with BHL.

![image](https://user-images.githubusercontent.com/60008120/197962629-2ad4d80c-07b6-4c63-8746-37364c08848c.png)

**Comment by rdmpage** [comment]
@Archilegt Exactly what gets a DOI is something BHL is talking about, and the answer isn't always obvious. This is particularly the case when retrospectively assigning DOIs to scanned content (for example, there may be multiple copies of the same thing, do they each get a DOI? do we have a DOI for the whole set? etc.).

> I am very tired of not having a direct communication channel with BHL.

What sort of channel would work? Are you thinking of something like the [GBIF community forum](https://discourse.gbif.org)?

**Comment by Archilegt** [comment]
> Exactly what gets a DOI is something BHL is talking about

If we don't see BHL talking about it, we cannot give input. Where is that conversation happening? Is it open to contributions? Has it been advertised? Has BHL tried reaching the broader community of users?

> What sort of channel would work?

Simple: A BHL GitHub repository. Neither I nor anyone should have to be writing scattered posts in BioStor's or GNA's GitHub repositories with the hope of indirectly reaching BHL. BHL issues should go to a BHL GitHub, so that we can guarantee that they reach BHL, that the discussion is open and receives multiple input, and that we can monitor how long issues take to solve.

**Comment by mlichtenberg** [comment]
I have tested the BHL feedback form twice now (once when the problem was first reported and again this morning).  I have been unable to produce an error.  Both times my submission was accepted without issue.  In addition, BHL regularly receives messages submitted via that form.

I have checked the logs and found exactly three errors produced by the feedback form in the last six months.  One in May, one in July, and one this morning.  In each case, the error was an odd... possibly transient... error that will be difficult to track down without additional information.  Honestly, they look more like background noise (for example, a server was being rebooted, or there was a hosting site network issue) than indications of a problem with the form.

So, @Archilegt, can you tell me exactly what data you attempted to submit?  And what "subject" you selected on the form?  I find it hard to imagine a scenario where your browser/OS would matter, but I'll take that information as well.  Basically, any additional information you can provide will be helpful.

Thanks.

**Comment by Archilegt** [comment]
Trying BHL's feedback form again, subject "Bibliographic issue", from the same physical location, laptop, and browser than yesterday. Yesterday I tried the form with the subject "Scanning request".

![image](https://user-images.githubusercontent.com/60008120/198201241-ef585099-a1d7-4978-8c81-0b274bd63484.png)

The submission worked.

![image](https://user-images.githubusercontent.com/60008120/198201341-9f758a63-01e5-4886-a8c8-96daa5bf6909.png)

I will try the feedback form, subject "Scanning request", from a different physical location today.

**Comment by Archilegt** [comment]
Trying scanning request from a different location. Other settings equal to yesterday.

![image](https://user-images.githubusercontent.com/60008120/198210232-d9cab72c-53ff-43b5-ad7d-fae745d27cdd.png)

This time it worked.

![image](https://user-images.githubusercontent.com/60008120/198210350-94357420-5d53-462c-affb-1cf7b7316fe8.png)

Additionally, it is worth mentioning that the "Sorry! Something unexpected..." error happened yesterday while trying to reach simple BHL pages. I don't know what this intermittent error / outage is, but it may be related to more than just the feedback form.

**Comment by mlichtenberg** [comment]
"Additionally, it is worth mentioning that the "Sorry! Something unexpected..." error happened yesterday while trying to reach simple BHL pages."   Ah-ha!  There's the information I needed!  Very likely the problem is not with the feedback form.  I suspect that errors occurring there are a symptom of something else.  @Archilegt, thank you for re-trying the form, and for the additional information.
