### ISSUE TITLE
Sherborn & Woodward (1901) study case

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#110]
**How to best model this reference?:**
Sherborn C. D., Woodward B. B. (1901): Dates of publication of the zoological and botanical portions of some French voyages. – Part II. Ferret and Galinier’s ‘Voyage en Abyssinie’; Lefebvre’s ‘Voyage en Abyssinie’; ‘Exploration scientifique de l’Algérie’; Castelnau’s ‘Amérique du Sud’; Dumont d’Urville’s ‘Voyage de l’Astrolabe’; Laplace’s ‘Voyage sur la Favorite’; Jacquemont’s ‘Voyage dans l’Inde’; Tréhouart’s ‘Commission scientifique d’Islande’; Cailliaud, ‘Voyage à Méroé’; ‘Expédition scientifique de Morée’; Fabre, ‘Commission scientifique du Nord’; Du Petit-Thouars, ‘Voyage de la Vénus’; and on the dates of the ‘Faune Française.’ _The Annals and Magazine of Natural History, ser. 7_, 8: [161](https://www.biodiversitylibrary.org/page/29980205)-164, [333](https://www.biodiversitylibrary.org/page/29980389)-336, [491](https://www.biodiversitylibrary.org/page/29980553)-494.

The work was published in three "parts" (not related to the Part II in the title), all with the same title. The parts are already identified in BHL.
1. https://www.biodiversitylibrary.org/part/68312
2. https://www.biodiversitylibrary.org/part/68333
3. https://www.biodiversitylibrary.org/part/68347

Regarding these three "parts" of Sherborn & Woodward (1901), and thinking of similar cases among Verhoeff's publications, I would tend to leave the first "part" with the textual title, then add "[Continuation]" to the title of the second "part" and "[Conclusion]" to the title of the third "part". Does this make sense? At the moment, "parts" 1 and 2 have the same title. "Part" 3 has the title "Miscellaneous" and comprises two different publications, one being the conclusion of Sherborn & Woodward (1901), pages 491-494, the other being a "Corrigenda...", pages 494-496. It needs to be split into its components.
I also think that there is a "same as" relation to visualize otherwise disconnected "parts" together on BHL landing pages. Correct? If so, it could be used for these three "parts".

**Comment by rdmpage** [comment]
@Archilegt My instinct is to leave the titles as they are. If the articles themselves include qualifiers such as "continued" then I'd include them. Otherwise it feels like the classic problem of overloading a data field (`title`) with stuff that doesn't belong there. IMHO that never ends well.

The reason for "Miscellaneous" is there is a DOI for that set of pages and that's what I've followed here. Sometimes DOIs assigned by commercial publishers don't align with our expectations of articles. We could partition the content further by creating parts for the two articles within "Miscellaneous".

I don't think "sameAs" is appropriate here, this is a series of distinct items, not a set of things that are the same. This is the sort of relationship perhaps best modelled in Wikidata, either by have a "series" item that includes all the individual articles, or including properties to make the articles a doubly linked list (i.e., "follows"/"is followed by").
