### ISSUE TITLE
Fully index Amphibian & Reptile Conservation

### ISSUE THREAD

**Issue by suwiding** [rdmpage/biostor#16]
As discussed in a recent email, please fully index Amphibian & Reptile Conservation in BioStor and BHL.

**Comment by rdmpage** [comment]
@suwiding It would be helpful if there was some starting data, such as a list of articles in EndNote format from Web of Science. That list is likely incomplete, so additional data will need to be scrapped from http://amphibian-reptile-conservation.org/archive.html

**Comment by rdmpage** [comment]
This journal seems to have flirted with both DOIs (which don't resolve) and Pubmed Central, see http://www.ncbi.nlm.nih.gov/pmc/issues/8454/

**Comment by rdmpage** [comment]
@suwiding I've added more articles from this journal. I'm technically on holiday and without my computer, but managed to do this using Coda and DraftCode on my iPad. There will be some missed articles, notably because the journal pagination starts from 1 with every issue, which causes problems for the algorithm BioStor uses to locate articles.

**Comment by trosesandler** [comment]
Hi Rod

I was just checking where you are with this journal and indexing.  I identified about 20 citations that are still missing in BHL and was wondering if I should try to manually enter them through the BHL admin dashboard (although that's a very inefficient process because of the requirement to research and match up all the author names).  Attached is the list of ones I identified.  Can you let me know if you've done all you can all your end to automate the process of finding them?  Thanks!  TRish
[Amphibian and Reptile Conservation articles to upload.docx](https://github.com/rdmpage/biostor/files/523045/Amphibian.and.Reptile.Conservation.articles.to.upload.docx)

**Comment by rdmpage** [comment]
Hi Trish, I've added the articles in the Word file to BioStor. Having a photograph as the first page of the article really complicate life :O

**Comment by trosesandler** [comment]
Terrific! Thanks Rod.  yes its rather strange how there is a pg with a photograph followed by the actual article throughout their journal.
