### ISSUE TITLE
Entomological News articles lacking author metadata

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#99]
Entomological News articles are lacking author metadata. Is this an error or was there a rationale behind not adding the authors to the references?

Example:
A new millipede of the genus Cylindrodesmus from Palmyra Island
Published in Entomological News 65 pages 65-67 ( 1954 ) 
https://biostor.org/reference/84413

I would appreciate if this article is updated.
Missing author string: Ralph V. Chamberlin

Additionally, the "Cite" button seems unresponsive.

**Comment by rdmpage** [comment]
Author names were lacking from the metadata used to find the articles (in this case the data was from ION). Finding complete metadata for articles is the major obstacle to locating articles in BHL, so I take whatever I can get.

**Comment by swlny** [comment]
Added author to article in BHL. See https://www.biodiversitylibrary.org/part/38992

**Comment by rdmpage** [comment]
I've added the author to BioStor. 

@swlny for BioStor articles I think it makes sense to fix the problem in BioStor, which then automatically updates BHL within 24 hours. Otherwise we end up duplicating effort because changes made directly to parts in BHL aren't picked up by BioStor.

If the part has been defined on the BHL platform then it makes sense to fix it on BHL.
